// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateCelestialBodyData, CreateCelestialBodyResponses, CreatePlanetData, CreatePlanetErrors, CreatePlanetResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeletePlanetData, DeletePlanetErrors, DeletePlanetResponses, GetAllDataData, GetAllDataResponses, GetMeData, GetMeErrors, GetMeResponses, GetPlanetData, GetPlanetErrors, GetPlanetResponses, GetTokenData, GetTokenErrors, GetTokenResponses, UpdatePlanetData, UpdatePlanetErrors, UpdatePlanetResponses, UploadImageData, UploadImageErrors, UploadImageResponses } from './types.gen';
import { zCreateCelestialBodyBody, zCreateCelestialBodyResponse, zCreatePlanetBody, zCreatePlanetResponse, zCreateUserBody, zCreateUserResponse, zDeletePlanetPath, zDeletePlanetResponse, zGetAllDataQuery, zGetAllDataResponse, zGetMeResponse, zGetPlanetPath, zGetPlanetResponse, zGetTokenBody, zGetTokenResponse, zUpdatePlanetBody, zUpdatePlanetPath, zUpdatePlanetResponse, zUploadImageBody, zUploadImagePath, zUploadImageResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all planets
 *
 * It's easy to say you know them all, but do you really? Retrieve all the planets and check whether you missed one.
 */
export const getAllData = <ThrowOnError extends boolean = true>(options?: Options<GetAllDataData, ThrowOnError>) => (options?.client ?? client).get<GetAllDataResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zGetAllDataQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetAllDataResponse.parseAsync(data),
    url: '/planets',
    ...options
});

/**
 * Create a planet
 *
 * Time to play god and create a new planet. What do you think? Ah, don't think too much. What could go wrong anyway?
 */
export const createPlanet = <ThrowOnError extends boolean = true>(options?: Options<CreatePlanetData, ThrowOnError>) => (options?.client ?? client).post<CreatePlanetResponses, CreatePlanetErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreatePlanetBody.optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreatePlanetResponse.parseAsync(data),
    security: [
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' },
        {
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        },
        { name: 'X-API-Key', type: 'apiKey' },
        {
            in: 'cookie',
            name: 'api_key',
            type: 'apiKey'
        },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'bearer', type: 'http' }
    ],
    url: '/planets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete a planet
 *
 * This endpoint was used to delete planets. Unfortunately, that caused a lot of trouble for planets with life. So, this endpoint is now deprecated and should not be used anymore.
 */
export const deletePlanet = <ThrowOnError extends boolean = true>(options: Options<DeletePlanetData, ThrowOnError>) => (options.client ?? client).delete<DeletePlanetResponses, DeletePlanetErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zDeletePlanetPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zDeletePlanetResponse.parseAsync(data),
    security: [
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' },
        {
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        },
        { name: 'X-API-Key', type: 'apiKey' },
        {
            in: 'cookie',
            name: 'api_key',
            type: 'apiKey'
        },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'bearer', type: 'http' }
    ],
    url: '/planets/{planetId}',
    ...options
});

/**
 * Get a planet
 *
 * You'll better learn a little bit more about the planets. It might come in handy once space travel is available for everyone.
 */
export const getPlanet = <ThrowOnError extends boolean = true>(options: Options<GetPlanetData, ThrowOnError>) => (options.client ?? client).get<GetPlanetResponses, GetPlanetErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zGetPlanetPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetPlanetResponse.parseAsync(data),
    url: '/planets/{planetId}',
    ...options
});

/**
 * Update a planet
 *
 * Sometimes you make mistakes, that's fine. No worries, you can update all planets.
 */
export const updatePlanet = <ThrowOnError extends boolean = true>(options: Options<UpdatePlanetData, ThrowOnError>) => (options.client ?? client).put<UpdatePlanetResponses, UpdatePlanetErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUpdatePlanetBody.optional(),
        path: zUpdatePlanetPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zUpdatePlanetResponse.parseAsync(data),
    security: [
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' },
        {
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        },
        { name: 'X-API-Key', type: 'apiKey' },
        {
            in: 'cookie',
            name: 'api_key',
            type: 'apiKey'
        },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'bearer', type: 'http' }
    ],
    url: '/planets/{planetId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload an image to a planet
 *
 * Got a crazy good photo of a planet? Share it with the world!
 */
export const uploadImage = <ThrowOnError extends boolean = true>(options: Options<UploadImageData, ThrowOnError>) => (options.client ?? client).post<UploadImageResponses, UploadImageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    requestValidator: async (data) => await z.object({
        body: zUploadImageBody.optional(),
        path: zUploadImagePath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zUploadImageResponse.parseAsync(data),
    security: [
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' },
        {
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        },
        { name: 'X-API-Key', type: 'apiKey' },
        {
            in: 'cookie',
            name: 'api_key',
            type: 'apiKey'
        },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'bearer', type: 'http' }
    ],
    url: '/planets/{planetId}/image',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Create a celestial body
 */
export const createCelestialBody = <ThrowOnError extends boolean = true>(options: Options<CreateCelestialBodyData, ThrowOnError>) => (options.client ?? client).post<CreateCelestialBodyResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateCelestialBodyBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateCelestialBodyResponse.parseAsync(data),
    security: [
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' },
        {
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        },
        { name: 'X-API-Key', type: 'apiKey' },
        {
            in: 'cookie',
            name: 'api_key',
            type: 'apiKey'
        },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'bearer', type: 'http' }
    ],
    url: '/celestial-bodies',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a user
 *
 * Time to create a user account, eh?
 */
export const createUser = <ThrowOnError extends boolean = true>(options?: Options<CreateUserData, ThrowOnError>) => (options?.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateUserBody.optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateUserResponse.parseAsync(data),
    url: '/user/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get a token
 *
 * Yeah, this is the boring security stuff. Just get your super secret token and move on.
 */
export const getToken = <ThrowOnError extends boolean = true>(options?: Options<GetTokenData, ThrowOnError>) => (options?.client ?? client).post<GetTokenResponses, GetTokenErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zGetTokenBody.optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetTokenResponse.parseAsync(data),
    url: '/auth/token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get authenticated user
 *
 * Find yourself they say. That's what you can do here.
 */
export const getMe = <ThrowOnError extends boolean = true>(options?: Options<GetMeData, ThrowOnError>) => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetMeResponse.parseAsync(data),
    security: [
        { scheme: 'basic', type: 'http' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'bearer', type: 'http' },
        { name: 'X-API-Key', type: 'apiKey' },
        {
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }
    ],
    url: '/me',
    ...options
});
