// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://galaxy.scalar.com' | '{protocol}://void.scalar.com/{path}' | (string & {});
};

export type Webhooks = PostNewPlanetWebhookRequest;

/**
 * A user
 */
export type User = {
    readonly id?: number;
    name?: string;
};

/**
 * Credentials to authenticate a user
 */
export type Credentials = {
    email: string;
};

/**
 * A token to authenticate a user
 */
export type Token = {
    token?: string;
};

/**
 * A celestial body which can be either a planet or a satellite
 */
export type CelestialBody = ({
    type: 'terrestrial' | 'gas_giant' | 'ice_giant' | 'dwarf' | 'super_earth';
} & Planet) | ({
    type: 'moon' | 'asteroid' | 'comet';
} & Satellite);

/**
 * A planet in the Scalar Galaxy
 */
export type Planet = {
    readonly id: number;
    name: string;
    description?: string | null;
    type?: 'terrestrial' | 'gas_giant' | 'ice_giant' | 'dwarf' | 'super_earth';
    /**
     * A score from 0 to 1 indicating potential habitability
     */
    habitabilityIndex?: number;
    physicalProperties?: {
        /**
         * Mass in Earth masses (must be greater than 0)
         */
        mass?: number;
        /**
         * Radius in Earth radii (must be greater than 0)
         */
        radius?: number;
        /**
         * Surface gravity in Earth g
         */
        gravity?: number;
        temperature?: {
            /**
             * Minimum temperature in Kelvin
             */
            min?: number;
            /**
             * Maximum temperature in Kelvin
             */
            max?: number;
            /**
             * Average temperature in Kelvin
             */
            average?: number;
            [key: string]: number | undefined;
        };
        [key: string]: number | number | {
            /**
             * Minimum temperature in Kelvin
             */
            min?: number;
            /**
             * Maximum temperature in Kelvin
             */
            max?: number;
            /**
             * Average temperature in Kelvin
             */
            average?: number;
            [key: string]: number | undefined;
        } | undefined;
    };
    /**
     * Atmospheric composition
     */
    atmosphere?: Array<{
        compound?: string;
        percentage?: number;
        [key: string]: string | number | undefined;
    }>;
    discoveredAt?: string;
    image?: string | null;
    satellites?: Array<Satellite>;
    creator?: User;
    tags?: Array<string>;
    readonly lastUpdated?: string;
    /**
     * URL which gets invoked upon a successful operation
     */
    successCallbackUrl?: string;
    /**
     * URL which gets invoked upon a failed operation
     */
    failureCallbackUrl?: string;
};

/**
 * Every satellite in the Scalar Galaxy
 */
export type Satellite = {
    readonly id?: number;
    name: string;
    description?: string | null;
    /**
     * Diameter in kilometers
     */
    diameter?: number;
    type?: 'moon' | 'asteroid' | 'comet';
    orbit?: {
        planet?: Planet;
        /**
         * Orbital period in Earth days
         */
        orbitalPeriod?: number;
        /**
         * Average distance from the planet in kilometers
         */
        distance?: number;
    };
};

/**
 * A paginated resource
 */
export type PaginatedResource = {
    meta?: {
        limit?: number;
        offset?: number;
        total?: number;
        next?: string | null;
    };
};

/**
 * Message about an image upload
 */
export type ImageUploadedMessage = {
    message?: string;
    /**
     * The URL where the uploaded image can be accessed
     */
    imageUrl?: string;
    /**
     * Timestamp when the image was uploaded
     */
    uploadedAt?: string;
    /**
     * Size of the uploaded image in bytes
     */
    fileSize?: number;
    /**
     * The content type of the uploaded image
     */
    mimeType?: string;
};

/**
 * RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807)
 */
export type BadRequestError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
};

/**
 * Error response for forbidden access (RFC 7807). Returned when the user does not have permission to access the requested resource.
 */
export type ForbiddenError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
};

/**
 * Error response for resource not found (RFC 7807). Returned when the requested resource does not exist.
 */
export type NotFoundError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
};

/**
 * Error response for unauthorized access (RFC 7807). Returned when authentication is required or has failed.
 */
export type UnauthorizedError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
};

/**
 * Error response for resource conflicts (RFC 7807). Returned when the request conflicts with the current state of the resource.
 */
export type Conflict = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
};

/**
 * Error response for unprocessable entity (RFC 7807). Returned when the request is well-formed but contains semantic errors.
 */
export type UnprocessableEntity = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
};

/**
 * Error response for rate limiting (RFC 7807). Returned when the client has exceeded the rate limit for requests.
 */
export type TooManyRequestsError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
};

/**
 * A user
 */
export type UserWritable = {
    name?: string;
};

/**
 * Credentials to authenticate a user
 */
export type CredentialsWritable = {
    email: string;
    password: string;
};

/**
 * A celestial body which can be either a planet or a satellite
 */
export type CelestialBodyWritable = ({
    type: 'terrestrial' | 'gas_giant' | 'ice_giant' | 'dwarf' | 'super_earth';
} & PlanetWritable) | ({
    type: 'moon' | 'asteroid' | 'comet';
} & SatelliteWritable);

/**
 * A planet in the Scalar Galaxy
 */
export type PlanetWritable = {
    name: string;
    description?: string | null;
    type?: 'terrestrial' | 'gas_giant' | 'ice_giant' | 'dwarf' | 'super_earth';
    /**
     * A score from 0 to 1 indicating potential habitability
     */
    habitabilityIndex?: number;
    physicalProperties?: {
        /**
         * Mass in Earth masses (must be greater than 0)
         */
        mass?: number;
        /**
         * Radius in Earth radii (must be greater than 0)
         */
        radius?: number;
        /**
         * Surface gravity in Earth g
         */
        gravity?: number;
        temperature?: {
            /**
             * Minimum temperature in Kelvin
             */
            min?: number;
            /**
             * Maximum temperature in Kelvin
             */
            max?: number;
            /**
             * Average temperature in Kelvin
             */
            average?: number;
            [key: string]: number | undefined;
        };
        [key: string]: number | number | {
            /**
             * Minimum temperature in Kelvin
             */
            min?: number;
            /**
             * Maximum temperature in Kelvin
             */
            max?: number;
            /**
             * Average temperature in Kelvin
             */
            average?: number;
            [key: string]: number | undefined;
        } | undefined;
    };
    /**
     * Atmospheric composition
     */
    atmosphere?: Array<{
        compound?: string;
        percentage?: number;
        [key: string]: string | number | undefined;
    }>;
    discoveredAt?: string;
    image?: string | null;
    satellites?: Array<SatelliteWritable>;
    creator?: UserWritable;
    tags?: Array<string>;
    /**
     * URL which gets invoked upon a successful operation
     */
    successCallbackUrl?: string;
    /**
     * URL which gets invoked upon a failed operation
     */
    failureCallbackUrl?: string;
};

/**
 * Every satellite in the Scalar Galaxy
 */
export type SatelliteWritable = {
    name: string;
    description?: string | null;
    /**
     * Diameter in kilometers
     */
    diameter?: number;
    type?: 'moon' | 'asteroid' | 'comet';
    orbit?: {
        planet?: PlanetWritable;
        /**
         * Orbital period in Earth days
         */
        orbitalPeriod?: number;
        /**
         * Average distance from the planet in kilometers
         */
        distance?: number;
    };
};

/**
 * The ID of the planet to get
 */
export type PlanetId = number;

/**
 * The number of items to return
 */
export type Limit = number;

/**
 * The number of items to skip before starting to collect the result set
 */
export type Offset = number;

export type GetAllDataData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The number of items to return
         */
        limit?: number;
        /**
         * The number of items to skip before starting to collect the result set
         */
        offset?: number;
    };
    url: '/planets';
};

export type GetAllDataResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<Planet>;
    } & PaginatedResource;
};

export type GetAllDataResponse = GetAllDataResponses[keyof GetAllDataResponses];

export type CreatePlanetData = {
    /**
     * Planet
     */
    body?: PlanetWritable;
    path?: never;
    query?: never;
    url: '/planets';
};

export type CreatePlanetErrors = {
    /**
     * Bad Request
     */
    400: BadRequestError;
    /**
     * Forbidden
     */
    403: ForbiddenError;
};

export type CreatePlanetError = CreatePlanetErrors[keyof CreatePlanetErrors];

export type CreatePlanetResponses = {
    /**
     * Created
     */
    201: Planet;
};

export type CreatePlanetResponse = CreatePlanetResponses[keyof CreatePlanetResponses];

export type DeletePlanetData = {
    body?: never;
    path: {
        /**
         * The ID of the planet to get
         */
        planetId: number;
    };
    query?: never;
    url: '/planets/{planetId}';
};

export type DeletePlanetErrors = {
    /**
     * Not Found
     */
    404: NotFoundError;
};

export type DeletePlanetError = DeletePlanetErrors[keyof DeletePlanetErrors];

export type DeletePlanetResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePlanetResponse = DeletePlanetResponses[keyof DeletePlanetResponses];

export type GetPlanetData = {
    body?: never;
    path: {
        /**
         * The ID of the planet to get
         */
        planetId: number;
    };
    query?: never;
    url: '/planets/{planetId}';
};

export type GetPlanetErrors = {
    /**
     * Not Found
     */
    404: NotFoundError;
};

export type GetPlanetError = GetPlanetErrors[keyof GetPlanetErrors];

export type GetPlanetResponses = {
    /**
     * Planet Found
     */
    200: Planet;
};

export type GetPlanetResponse = GetPlanetResponses[keyof GetPlanetResponses];

export type UpdatePlanetData = {
    /**
     * New information about the planet
     */
    body?: PlanetWritable;
    path: {
        /**
         * The ID of the planet to get
         */
        planetId: number;
    };
    query?: never;
    url: '/planets/{planetId}';
};

export type UpdatePlanetErrors = {
    /**
     * Bad Request
     */
    400: BadRequestError;
    /**
     * Forbidden
     */
    403: ForbiddenError;
    /**
     * Not Found
     */
    404: NotFoundError;
};

export type UpdatePlanetError = UpdatePlanetErrors[keyof UpdatePlanetErrors];

export type UpdatePlanetResponses = {
    /**
     * Planet updated successfully
     */
    200: Planet;
};

export type UpdatePlanetResponse = UpdatePlanetResponses[keyof UpdatePlanetResponses];

export type UploadImageData = {
    /**
     * Image to upload
     */
    body?: {
        /**
         * The image file to upload
         */
        image?: Blob | File;
    };
    path: {
        /**
         * The ID of the planet to get
         */
        planetId: number;
    };
    query?: never;
    url: '/planets/{planetId}/image';
};

export type UploadImageErrors = {
    /**
     * Bad Request
     */
    400: BadRequestError;
    /**
     * Forbidden
     */
    403: ForbiddenError;
    /**
     * Not Found
     */
    404: NotFoundError;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
    /**
     * Image uploaded
     */
    200: ImageUploadedMessage;
};

export type UploadImageResponse = UploadImageResponses[keyof UploadImageResponses];

export type CreateCelestialBodyData = {
    /**
     * Celestial body to create
     */
    body: CelestialBodyWritable;
    path?: never;
    query?: never;
    url: '/celestial-bodies';
};

export type CreateCelestialBodyResponses = {
    /**
     * Celestial body created
     */
    201: CelestialBody;
};

export type CreateCelestialBodyResponse = CreateCelestialBodyResponses[keyof CreateCelestialBodyResponses];

export type CreateUserData = {
    /**
     * User to create
     */
    body?: UserWritable & CredentialsWritable;
    path?: never;
    query?: never;
    url: '/user/signup';
};

export type CreateUserErrors = {
    /**
     * Bad Request
     */
    400: BadRequestError;
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Forbidden
     */
    403: ForbiddenError;
    /**
     * Conflict
     */
    409: Conflict;
    /**
     * Unprocessable Entity
     */
    422: UnprocessableEntity;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * User account created successfully
     */
    201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetTokenData = {
    /**
     * Body for credentials to authenticate a user
     */
    body?: CredentialsWritable;
    path?: never;
    query?: never;
    url: '/auth/token';
};

export type GetTokenErrors = {
    /**
     * Bad Request
     */
    400: BadRequestError;
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Forbidden
     */
    403: ForbiddenError;
    /**
     * Too Many Requests
     */
    429: TooManyRequestsError;
};

export type GetTokenError = GetTokenErrors[keyof GetTokenErrors];

export type GetTokenResponses = {
    /**
     * Token Created
     */
    201: Token;
};

export type GetTokenResponse = GetTokenResponses[keyof GetTokenResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Forbidden
     */
    403: ForbiddenError;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Authenticated user information retrieved successfully
     */
    200: User;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

/**
 * Information about a new planet
 */
export type PostNewPlanetWebhookPayload = PlanetWritable;

export type PostNewPlanetWebhookRequest = {
    body: PostNewPlanetWebhookPayload;
    key: 'newPlanet';
    path?: never;
    query?: never;
};
